# Generated by Django 3.2.5 on 2021-07-07 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=20)),
                ('Department', models.CharField(max_length=20)),
                ('Course', models.CharField(max_length=10)),
                ('Year', models.IntegerField()),
            ],
        ),
    ]
